### ISSUE TITLE
Add More Baubles functionallity

### ISSUE THREAD

**Issue by tyler489** [svennieke/StatuesMod#2]
Something like tier 1 statues are purely decritve when worn. tier 2 play sounds. tier 3 plays sounds when items are given and tier 4 just gives items without sounds.

**Comment by DWX12** [comment]
I believe this goes with my idea I discussed with you on your discord server about having effects when having the statues equipped. I know you guys were against it, but maybe you'll reconsider. It would encourage people to actually wear them as baubles as they would do something rather than just being purely decorative.

Might I also suggest mobs of the statue's type having a low chance of spawning by a player that's wearing them just as they have a chance of spawning when repeatedly interacted with. Also a config option to stop mobs from spawning when interacted with.

**Comment by svennieke** [comment]
In the early stages of the mod we decided against this, we want to encourage player interaction with the statues rather than having things get generated by wearing a statue in a bauble slot.
